default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: lint
        name: Lint
        entry: pnpm run lint
        language: system
        pass_filenames: true
      - id: rust_fmt
        name: Cargo fmt
        entry: cargo fmt
        language: system
        pass_filenames: false
      - id: rust_check
        name: Cargo check
        entry: cargo check
        language: system
        pass_filenames: false

      - id: test_wasm
        name: Cargo test
        entry: cargo test
        language: system
        pass_filenames: false

      - id: build
        name: Build
        entry: pnpm run build
        language: system
        pass_filenames: false
        stages:
          - pre-push
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        stages:
          - pre-commit
